#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps 
if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi
if [ -f $sysmodmap ]; then
	xrdb -merge $sysmodmap
fi
if [ -f $userresources ]; then
	xrdb -merge $userresources
fi
if [ -f $usermodmap ]; then
	xrdb -merge $usermodmap
fi

# ensure scripts in /etx/X11/xinit/xinitrc.d are sourced
if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etx/X11/xinit/xinitrc.d/?*.sh ; do 
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

# uncomment following command to crate an i3 log file
#exec i3 >~/i3log-$(date +'%F-%k-%M-%S') 2>&1 
exec i3
