config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_config:
    src: config/i3/config
    dst: ~/.config/i3/config
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_polybar_config:
    src: config/polybar/config
    dst: ~/.config/polybar/config
  f_launch.sh:
    src: config/polybar/launch.sh
    dst: ~/.config/polybar/launch.sh
  f_openweathermap-fullfeatured.sh:
    src: config/polybar/scripts/openweathermap-fullfeatured.sh
    dst: ~/.config/polybar/scripts/openweathermap-fullfeatured.sh
  f_spotify_status.py:
    src: config/polybar/scripts/spotify_status.py
    dst: ~/.config/polybar/scripts/spotify_status.py
  f_updates-pacman-aurhelper.sh:
    src: config/polybar/scripts/updates-pacman-aurhelper.sh
    dst: ~/.config/polybar/scripts/updates-pacman-aurhelper.sh
profiles:
  joshpc:
    dotfiles:
    - f_vimrc
    - f_bashrc
    - f_config
    - f_xresources
    - f_xinitrc
    - f_polybar_config
    - f_launch.sh
    - f_openweathermap-fullfeatured.sh
    - f_spotify_status.py
    - f_updates-pacman-aurhelper.sh
